CFLAGS = -O3 -std=c++11 -Wall

day4: day4-1.cpp day4-2.cpp
	g++ $(CFLAGS) day4-1.cpp -o day4-1
	g++ $(CFLAGS) day4-2.cpp -o day4-2

run1: day4-1
	./day4-1 < input.txt
run2: day4-2
	./day4-2 < input.txt


