CFLAGS = -O3 -std=c++11 -Wall

day3: day3-1.cpp day3-2.cpp
	g++ $(CFLAGS) day3-1.cpp -o day3-1
	g++ $(CFLAGS) day3-2.cpp -o day3-2

run1: day3-1
	./day3-1 < input.txt
run2: day3-2
	./day3-2 < input.txt


