CFLAGS = -O3 -std=c++11 -Wall

day1: day1-1.cpp day1-2.cpp
	g++ $(CFLAGS) day1-1.cpp -o day1-1
	g++ $(CFLAGS) day1-2.cpp -o day1-2

run1: day1-1
	./day1-1 < input.txt
run2: day2-2
	./day1-2 < input.txt


